services:
  whisperx:
    container_name: "whisperx"
    entrypoint:
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:8000"
      - "--workers"
      - "1"
      - "--timeout"
      - "0"
      - "app.main:app"
      - "-k"
      - "uvicorn.workers.UvicornWorker"
    environment:
      - "WHISPER_MODEL=large-v2"
    image: "whisperx-service2:2024-11-16"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "bridge"
    ports:
      - "8000:8000/tcp"
    restart: "unless-stopped"
    volumes:
      - "/data/whisperx/cache:/root/.cache"
      - "/data/whisperx/tmp:/tmp"
    working_dir: "/app"
version: "3.6"
