name: Build
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'
  push:
    branches:
       - "main"
    tags:
      - "v*"

jobs:
    release_server:
        runs-on: linux-ubuntu22.04
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }}
            - name: Build and push
              uses: docker/build-push-action@v3
              env:
                TAG: ${{ github.event.inputs.tags || 'latest'}} 
              with:
                context: .
                file: ./dockerfile
                push: true
                tags: beclab/whisper-api:${{env.TAG}}
                platforms: linux/amd64
