name: CI
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "app/**"
      - "tests/**"
      - "dockerfile"
      - "docker-compose.yml"
      - "requirements/**"
  workflow_dispatch: # Allows manual triggering of the workflow
permissions:
  contents: read
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    secrets:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
  build-and-test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: whisperx-fastapi:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run tests
        run: |
          docker run --env HF_TOKEN=${{ secrets.HF_TOKEN }} \
            --env WHISPER_MODEL=tiny \
            --env DEFAULT_LANG=en \
            --env DEVICE=cpu \
            --env COMPUTE_TYPE=int8 \
            --entrypoint /bin/bash whisperx-fastapi:latest \
            -c "pip install pytest==8.3.4 pytest-cov==6.0.0 && pytest"
