name: Build Status
on:
  workflow_call:
  push:
    branches-ignore:
      - main
    paths:
      - "app/**"
      - "tests/**"
      - "dockerfile"
      - "docker-compose.yml"
      - "requirements/**"
  pull_request:
    branches-ignore:
      - main
      - dev
    paths:
      - "app/**"
      - "dockerfile"
      - "docker-compose.yml"
      - "requirements/**"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      WHISPER_MODEL: tiny
      DEFAULT_LANG: en
      DEVICE: cpu
      COMPUTE_TYPE: int8
    steps:
      - uses: actions/checkout@v4
      - name: Check if HF_TOKEN secret is set
        run: |
          if [ -z "${{ secrets.HF_TOKEN }}" ]; then
            echo "::error::HF_TOKEN secret is not set or is empty."
            exit 1
          else
            echo "HF_TOKEN secret is set."
          fi
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}
      - run: echo "actor is:" ${{ github.actor }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements/**/*.txt"
          version: "0.6.6"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          python-version-file: "pyproject.toml"
      - name: Install Python dependencies
        run: uv pip install --system -r requirements/dev.txt
      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}
      - name: Check Hugging Face Token Validity
        run: huggingface-cli whoami
      - name: Run Ruff linter
        run: ruff check .
      - name: Run Ruff formatter check
        run: ruff format --check .
      - name: Run tests with coverage check
        run: |
          python -m coverage run --source=app -m pytest
          python -m coverage report --fail-under=55 --show-missing
